[Variables]
;Color used for large horizontal and vertical indicators
Clr.VLine=100,100,100,100
Clr.HLine=100,100,100,100

;===== Positioning options =====
;Cell Dimensions - The dimensions of the individual string meters.
C.w=16
C.h=16
;Spacers and bumper
;Vertical space between cells
Space.x=11
;Horizontal space between cells
Space.y=4
;Space on left and right of calendar
Bumper.x=20
;Space on top of calendar
Bumper.top=3
;Space on bottom of calendar
Bumper.bottom=0