[Variables]
;Date indicator line color
Clr.Hrl=128,192,255,160

;===== Positioning options =====
;Cell Dimensions - The dimensions of the individual string meters.
C.w=16
C.h=16
;Spacers and bumper
;Vertical space between cells
Space.x=11
;Horizontal space between cells
Space.y=4
;Space on left and right of calendar
Bumper.x=10
;Space on top of calendar
Bumper.top=3
;Space on bottom of calendar
Bumper.bottom=0